export const contactPageCopy = {
  en: {
    heroEyebrow: "Real Estate Contact",
    heroTitle: "Start the right property conversation.",
    heroLead:
      "Share the essentials for a property, project, materials, pricing, or market guidance request. We will route it to the right specialist path.",
    cardLabel: "Direct contact",
    cardAria: "Contact channels and request checklist",
    emailLabel: "Email",
    phoneLabel: "Phone",
    quickChecklist: ["Request type and location", "Budget, quantity, or project scope", "Timeline and preferred follow-up"],
    routingEyebrow: "Request routing",
    routingTitle: "Choose the closest path to first message practical.",
    formTitle: "Send your inquiry",
    formLead: "We review each request and follow up with the most relevant next step.",
    responseNote: "Property, project, materials, pricing, and market guidance requests all start here.",
    requestTypes: [
      { iconKey: "Building2", label: "Properties", tip: "Mention asset type (residential, commercial, investment), preferred area, budget range, and buying or leasing intent." },
      { iconKey: "ClipboardCheck", label: "Projects & Construction", tip: "Include site location, project stage, role needed (contractor, investor, coordinator), drawings or scope notes, and delivery timeline." },
      { iconKey: "PackageCheck", label: "Building Materials", tip: "List material categories, grade or specification, quantities, delivery destination, and any brand preferences." },
      { iconKey: "FileText", label: "Pricing Requests", tip: "Provide requirement scope, dimensions, quantities, acceptable alternatives, and expected quote deadline." },
      { iconKey: "BarChart3", label: "Market Guidance", tip: "Share the area of interest, asset class, investment purpose, budget range, and any timing considerations." },
      { iconKey: "MapPin", label: "Site Visit & Follow-up", tip: "Add preferred visit timing, decision maker availability, access details, and the best contact method for coordination." },
    ],
  },
  tr: {
    heroEyebrow: "Gayrimenkul İletişim",
    heroTitle: "Doğru gayrimenkul görüşmesini başlatın.",
    heroLead:
      "Gayrimenkul, proje, malzeme, fiyatlandırma veya pazar rehberliği talebi için temel bilgileri paylaşın. Doğru uzman yoluna yönlendireceğiz.",
    cardLabel: "Doğrudan iletişim",
    cardAria: "İletişim kanalları ve talep kontrol listesi",
    emailLabel: "E-posta",
    phoneLabel: "Telefon",
    quickChecklist: ["Talep türü ve konum", "Bütçe, miktar veya proje kapsamı", "Zaman çizelgesi ve tercih edilen takip"],
    routingEyebrow: "Talep yönlendirme",
    routingTitle: "İlk mesaj için en uygun yolu seçin.",
    formTitle: "Talebinizi gönderin",
    formLead: "Her talebi inceler ve en ilgili sonraki adımla geri dönüş yaparız.",
    responseNote: "Gayrimenkul, proje, malzeme, fiyatlandırma ve pazar rehberliği talepleri buradan başlar.",
    requestTypes: [
      { iconKey: "Building2", label: "Gayrimenkuller", tip: "Varlık türü (konut, ticari, yatırım), tercih edilen bölge, bütçe aralığı ve satın alma veya kiralama niyetini belirtin." },
      { iconKey: "ClipboardCheck", label: "Projeler ve İnşaat", tip: "Saha konumu, proje aşaması, gereken rol, çizim veya kapsam notları ve teslimat zaman çizelgesini ekleyin." },
      { iconKey: "PackageCheck", label: "Yapı Malzemeleri", tip: "Malzeme kategorileri, sınıf veya spesifikasyon, miktarlar, teslimat noktası ve marka tercihlerini listeleyin." },
      { iconKey: "FileText", label: "Fiyatlandırma Talepleri", tip: "Gereksinim kapsamı, boyutlar, miktarlar, kabul edilebilir alternatifler ve beklenen teklif son tarihini belirtin." },
      { iconKey: "BarChart3", label: "Pazar Rehberliği", tip: "İlgi alanı, varlık sınıfı, yatırım amacı, bütçe aralığı ve zamanlama hususlarını paylaşın." },
      { iconKey: "MapPin", label: "Saha Ziyareti ve Takip", tip: "Tercih edilen ziyaret zamanı, karar verici uygunluğu, erişim detayları ve en iyi iletişim yöntemini ekleyin." },
    ],
  },
  fa: {
    heroEyebrow: "تماس املاک",
    heroTitle: "گفتگوی درست ملک را آغاز کنید.",
    heroLead:
      "موارد ضروری برای درخواست ملک، پروژه، مصالح، قیمت‌گذاری یا راهنمای بازار را به اشتراک بگذارید. آن را به مسیر متخصص مناسب هدایت می‌کنیم.",
    cardLabel: "تماس مستقیم",
    cardAria: "کانال‌های تماس و چک‌لیست درخواست",
    emailLabel: "ایمیل",
    phoneLabel: "تلفن",
    quickChecklist: ["نوع درخواست و موقعیت", "بودجه، مقدار یا محدوده پروژه", "زمان‌بندی و پیگیری ترجیحی"],
    routingEyebrow: "مسیریابی درخواست",
    routingTitle: "نزدیک‌ترین مسیر را برای پیام اول انتخاب کنید.",
    formTitle: "ارسال درخواست",
    formLead: "هر درخواست را بررسی می‌کنیم و با مرتبط‌ترین گام بعدی پیگیری می‌کنیم.",
    responseNote: "درخواست‌های ملک، پروژه، مصالح، قیمت‌گذاری و راهنمای بازار همگی از اینجا شروع می‌شوند.",
    requestTypes: [
      { iconKey: "Building2", label: "املاک", tip: "نوع دارایی (مسکونی، تجاری، سرمایه‌گذاری)، منطقه ترجیحی، محدوده بودجه و قصد خرید یا اجاره را ذکر کنید." },
      { iconKey: "ClipboardCheck", label: "پروژه‌ها و ساخت‌وساز", tip: "موقعیت سایت، مرحله پروژه، نقش مورد نیاز، نقشه یا یادداشت محدوده و زمان‌بندی تحویل را شامل کنید." },
      { iconKey: "PackageCheck", label: "مصالح ساختمانی", tip: "دسته مصالح، درجه یا مشخصات، مقادیر، محل تحویل و ترجیحات برند را فهرست کنید." },
      { iconKey: "FileText", label: "درخواست قیمت", tip: "محدوده نیاز، ابعاد، مقادیر، جایگزین‌های قابل قبول و مهلت پیش‌فاکتور مورد انتظار را ارائه دهید." },
      { iconKey: "BarChart3", label: "راهنمای بازار", tip: "منطقه مورد علاقه، کلاس دارایی، هدف سرمایه‌گذاری، محدوده بودجه و ملاحظات زمان‌بندی را به اشتراک بگذارید." },
      { iconKey: "MapPin", label: "بازدید سایت و پیگیری", tip: "زمان بازدید ترجیحی، دسترسی تصمیم‌گیرنده، جزئیات دسترسی و بهترین روش تماس را اضافه کنید." },
    ],
  },
  ar: {
    heroEyebrow: "تواصل العقارات",
    heroTitle: "ابدأ المحادثة العقارية المناسبة.",
    heroLead:
      "شارك الأساسيات لطلب عقار أو مشروع أو مواد أو تسعير أو إرشاد السوق. سنوجهه إلى المسار المتخصص الصحيح.",
    cardLabel: "تواصل مباشر",
    cardAria: "قنوات التواصل وقائمة التحقق من الطلب",
    emailLabel: "البريد الإلكتروني",
    phoneLabel: "الهاتف",
    quickChecklist: ["نوع الطلب والموقع", "الميزانية أو الكمية أو نطاق المشروع", "الجدول الزمني والمتابعة المفضلة"],
    routingEyebrow: "توجيه الطلب",
    routingTitle: "اختر أقرب مسار للرسالة الأولى العملية.",
    formTitle: "أرسل استفسارك",
    formLead: "نراجع كل طلب ونتابع بالخطوة التالية الأكثر صلة.",
    responseNote: "طلبات العقارات والمشاريع والمواد والتسعير وإرشاد السوق تبدأ جميعها من هنا.",
    requestTypes: [
      { iconKey: "Building2", label: "العقارات", tip: "اذكر نوع الأصل (سكني، تجاري، استثماري) والمنطقة المفضلة ونطاق الميزانية ونية الشراء أو الإيجار." },
      { iconKey: "ClipboardCheck", label: "المشاريع والبناء", tip: "ضم موقع المشروع ومرحلة المشروع والدور المطلوب والمخططات أو ملاحظات النطاق والجدول الزمني للتسليم." },
      { iconKey: "PackageCheck", label: "مواد البناء", tip: "اذكر فئات المواد والدرجة أو المواصفات والكميات ووجهة التسليم وأي تفضيلات للعلامة." },
      { iconKey: "FileText", label: "طلبات التسعير", tip: "قدم نطاق المتطلبات والأبعاد والكميات والبدائل المقبولة والموعد النهائي المتوقع للعرض." },
      { iconKey: "BarChart3", label: "إرشاد السوق", tip: "شارك منطقة الاهتمام وفئة الأصل والغرض الاستثماري ونطاق الميزانية وأي اعتبارات توقيت." },
      { iconKey: "MapPin", label: "زيارة الموقع والمتابعة", tip: "أضف توقيت الزيارة المفضل وتوفر صانع القرار وتفاصيل الوصول وأفضل طريقة للتواصل." },
    ],
  },
};

export function getContactPageCopy(lang) {
  return contactPageCopy[lang] || contactPageCopy.en;
}
