const categoriesEn = [
  { iconKey: "Building2", label: "Property Markets", desc: "Residential, commercial, and investment asset classes reviewed by location quality, demand depth, and pricing context." },
  { iconKey: "TrendingUp", label: "Investment Landscape", desc: "Yield targets, holding period expectations, exit paths, and capital position reviewed before shortlisting options." },
  { iconKey: "ClipboardCheck", label: "Development Activity", desc: "Active construction corridors, land use changes, project pipeline, and zoning shifts that affect opportunity quality." },
  { iconKey: "PackageCheck", label: "Materials & Supply", desc: "Construction input costs, supply lead times, procurement availability, and material pricing trends by project stage." },
];

export const insightsPageCopy = {
  en: {
    heroEyebrow: "Market Intelligence",
    heroTitle: "Real Estate Insights & Investment Guidance",
    heroLead:
      "Practical market context for buyers, investors, and developers evaluating location quality, demand signals, and asset class positioning in Oman, Turkey, and the wider region.",
    statAssetClasses: "Asset Classes",
    statMarketSignals: "Market Signals",
    statFocusMarkets: "Focus Markets",
    statEvaluationSteps: "Evaluation Steps",
    panelLabel: "Market brief",
    panelTitle: "Read the opportunity before you move.",
    panelItems: ["Location quality and access", "Demand, yield, and resale depth", "Project pipeline and timing"],
    panelAria: "Market insight brief",
    categoriesEyebrow: "Insight Categories",
    categoriesTitle: "What we cover",
    categoriesLead: "Market context across property types, investment positions, development activity, and supply conditions.",
    marketsEyebrow: "Geographic Coverage",
    marketsTitle: "Markets we actively follow",
    marketsLead:
      "Our focus covers Oman, Turkey, GCC, and international investors comparing these markets. Each geography has distinct signals, ownership rules, and investment timing factors.",
    stepsEyebrow: "Market Evaluation",
    stepsTitle: "How to read an opportunity",
    stepsLead: "The four factors reviewed before recommending options to buyers, investors, or developers.",
    signalsEyebrow: "Signals",
    signalsTitle: "Key signals to monitor",
    signalsLead: "The factors that shift opportunity quality and investment timing in any market area.",
    prepEyebrow: "Preparation",
    prepTitle: "Come prepared, get better options",
    prepLead:
      "Clients who share key details upfront receive focused options rather than broad category lists. A clear investment brief lets us match location, asset class, and timing to real opportunities.",
    prepCardLabel: "Investment Brief Template",
    prepCardItems: [
      "Market: Muscat, Turkey, or GCC",
      "Asset: Residential · Commercial · Land",
      "Budget: OMR 50K – OMR 500K",
      "Purpose: Yield · Capital growth · Own use",
      "Timeline: Under 6 months",
    ],
    prepCardFooter: "A clear brief gets a focused shortlist — not a general search.",
    ctaEyebrow: "Next Step",
    ctaTitle: "Ready to evaluate your position?",
    ctaLead: "Share the location, asset class, budget range, and investment purpose. We will return with market context and relevant options.",
    contactUs: "Contact us",
    categories: categoriesEn,
    focusMarkets: [
      { name: "Muscat & Oman", note: "The primary market for international buyers, investors, and tenant-focused assets across freehold zones." },
      { name: "Istanbul & Turkey", note: "Active for development land, residential investment, and construction-linked projects in high-growth corridors." },
      { name: "GCC Region", note: "Cross-border commercial real estate and investment opportunities across Gulf markets and linked economies." },
      { name: "International Clients", note: "Diaspora and cross-border investors comparing Oman and Turkey positioning against home market benchmarks." },
    ],
    evaluationSteps: [
      { label: "Location Quality", desc: "Access routes, surrounding demand drivers, infrastructure investment, and catchment strength reviewed before pricing." },
      { label: "Demand Signals", desc: "Occupancy rates, buyer and tenant profile, absorption pace, and comparable rental depth in the immediate area." },
      { label: "Development Context", desc: "Nearby project pipeline, planned infrastructure changes, zoning activity, and the competitive supply position over 3–5 years." },
      { label: "Investment Case", desc: "Yield range, holding period logic, entry price relative to comparable exits, and risk-to-return fit for the investor profile." },
    ],
    marketSignals: [
      { label: "Infrastructure & Access", desc: "Road, metro, and utility development shifts that alter catchment value and rental demand." },
      { label: "Tenant & Buyer Demand", desc: "Absorption pace, occupancy depth, buyer type activity, and comparative vacancy by asset class." },
      { label: "Development Pipeline", desc: "Upcoming supply volume, completion timing, and how new projects compete with existing stock." },
      { label: "Comparable Pricing", desc: "Per-unit and per-square-meter transaction benchmarks and the direction of price movement." },
      { label: "Regulatory Environment", desc: "Ownership policy, visa-linked property programs, foreign investment rules, and local planning shifts." },
      { label: "Exit & Liquidity", desc: "Resale depth, days-to-sale in the target segment, buyer appetite, and realistic exit assumptions." },
    ],
    investmentPrepItems: [
      "Budget range and preferred financing method",
      "Target location or market area",
      "Preferred asset class — residential, commercial, or land",
      "Investment purpose — yield, capital growth, or own use",
      "Timeline and risk tolerance",
    ],
  },
  tr: {
    heroEyebrow: "Pazar İstihbaratı",
    heroTitle: "Gayrimenkul Görüşleri ve Yatırım Rehberliği",
    heroLead:
      "Umman, Türkiye ve daha geniş bölgede konum kalitesi, talep sinyalleri ve varlık sınıfı konumlandırmasını değerlendiren alıcılar, yatırımcılar ve geliştiriciler için pratik pazar bağlamı.",
    statAssetClasses: "Varlık Sınıfı",
    statMarketSignals: "Pazar Sinyali",
    statFocusMarkets: "Odak Pazar",
    statEvaluationSteps: "Değerlendirme Adımı",
    panelLabel: "Pazar özeti",
    panelTitle: "Harekete geçmeden önce fırsatı okuyun.",
    panelItems: ["Konum kalitesi ve erişim", "Talep, getiri ve yeniden satış derinliği", "Proje hattı ve zamanlama"],
    panelAria: "Pazar görüşü özeti",
    categoriesEyebrow: "Görüş Kategorileri",
    categoriesTitle: "Kapsadığımız alanlar",
    categoriesLead: "Gayrimenkul türleri, yatırım pozisyonları, geliştirme faaliyeti ve arz koşulları genelinde pazar bağlamı.",
    marketsEyebrow: "Coğrafi Kapsam",
    marketsTitle: "Aktif takip ettiğimiz pazarlar",
    marketsLead:
      "Odak noktamız Umman, Türkiye, KİK ve bu pazarları karşılaştıran uluslararası yatırımcıları kapsar. Her coğrafyanın farklı sinyalleri, mülkiyet kuralları ve yatırım zamanlama faktörleri vardır.",
    stepsEyebrow: "Pazar Değerlendirmesi",
    stepsTitle: "Bir fırsatı nasıl okursunuz",
    stepsLead: "Alıcılara, yatırımcılara veya geliştiricilere seçenek önermeden önce incelenen dört faktör.",
    signalsEyebrow: "Sinyaller",
    signalsTitle: "İzlenmesi gereken temel sinyaller",
    signalsLead: "Herhangi bir pazar alanında fırsat kalitesini ve yatırım zamanlamasını değiştiren faktörler.",
    prepEyebrow: "Hazırlık",
    prepTitle: "Hazırlıklı gelin, daha iyi seçenekler alın",
    prepLead:
      "Önemli detayları önceden paylaşan müşteriler geniş kategori listeleri yerine odaklı seçenekler alır. Net bir yatırım özeti konum, varlık sınıfı ve zamanlamayı gerçek fırsatlarla eşleştirmemizi sağlar.",
    prepCardLabel: "Yatırım Özeti Şablonu",
    prepCardItems: [
      "Pazar: Muscat, Türkiye veya KİK",
      "Varlık: Konut · Ticari · Arsa",
      "Bütçe: 50K – 500K OMR",
      "Amaç: Getiri · Sermaye büyümesi · Kendi kullanım",
      "Zaman: 6 ay altında",
    ],
    prepCardFooter: "Net bir özet odaklı kısa liste getirir — genel arama değil.",
    ctaEyebrow: "Sonraki Adım",
    ctaTitle: "Pozisyonunuzu değerlendirmeye hazır mısınız?",
    ctaLead: "Konum, varlık sınıfı, bütçe aralığı ve yatırım amacını paylaşın. Pazar bağlamı ve ilgili seçeneklerle döneceğiz.",
    contactUs: "Bize ulaşın",
    categories: [
      { iconKey: "Building2", label: "Gayrimenkul Pazarları", desc: "Konum kalitesi, talep derinliği ve fiyat bağlamına göre incelenen konut, ticari ve yatırım varlık sınıfları." },
      { iconKey: "TrendingUp", label: "Yatırım Ortamı", desc: "Kısa listeye almadan önce incelenen getiri hedefleri, tutma süresi beklentileri, çıkış yolları ve sermaye konumu." },
      { iconKey: "ClipboardCheck", label: "Geliştirme Faaliyeti", desc: "Fırsat kalitesini etkileyen aktif inşaat koridorları, arazi kullanım değişiklikleri, proje hattı ve imar değişimleri." },
      { iconKey: "PackageCheck", label: "Malzeme ve Arz", desc: "Proje aşamasına göre inşaat girdi maliyetleri, tedarik süreleri, tedarik uygunluğu ve malzeme fiyat trendleri." },
    ],
    focusMarkets: [
      { name: "Muscat ve Umman", note: "Uluslararası alıcılar, yatırımcılar ve kiracı odaklı varlıklar için birincil pazar." },
      { name: "İstanbul ve Türkiye", note: "Yüksek büyüme koridorlarında geliştirme arazisi, konut yatırımı ve inşaat bağlantılı projeler için aktif." },
      { name: "KİK Bölgesi", note: "Körfez pazarları ve bağlantılı ekonomiler genelinde sınır ötesi ticari gayrimenkul ve yatırım fırsatları." },
      { name: "Uluslararası Müşteriler", note: "Umman ve Türkiye konumlandırmasını ev pazarı kıyaslarıyla karşılaştıran diaspora ve sınır ötesi yatırımcılar." },
    ],
    evaluationSteps: [
      { label: "Konum Kalitesi", desc: "Fiyatlandırmadan önce erişim yolları, çevredeki talep sürücüleri, altyapı yatırımı ve catchment gücü incelenir." },
      { label: "Talep Sinyalleri", desc: "Doluluk oranları, alıcı ve kiracı profili, emilim hızı ve yakın bölgedeki kira derinliği." },
      { label: "Geliştirme Bağlamı", desc: "Yakın proje hattı, planlanan altyapı değişiklikleri, imar faaliyeti ve 3–5 yıllık rekabetçi arz konumu." },
      { label: "Yatırım Durumu", desc: "Getiri aralığı, tutma süresi mantığı, giriş fiyatının çıkışlarla karşılaştırılması ve yatırımcı profiline risk-getiri uyumu." },
    ],
    marketSignals: [
      { label: "Altyapı ve Erişim", desc: "Catchment değerini ve kira talebini değiştiren yol, metro ve altyapı gelişmeleri." },
      { label: "Kiracı ve Alıcı Talebi", desc: "Emilim hızı, doluluk derinliği, alıcı tipi aktivitesi ve varlık sınıfına göre boşluk karşılaştırması." },
      { label: "Geliştirme Hattı", desc: "Yaklaşan arz hacmi, tamamlanma zamanlaması ve yeni projelerin mevcut stokla rekabeti." },
      { label: "Karşılaştırılabilir Fiyatlandırma", desc: "Birim ve metrekare işlem kıyasları ve fiyat hareketinin yönü." },
      { label: "Düzenleyici Ortam", desc: "Mülkiyet politikası, vize bağlantılı programlar, yabancı yatırım kuralları ve yerel planlama değişimleri." },
      { label: "Çıkış ve Likidite", desc: "Yeniden satış derinliği, hedef segmentte satış süresi, alıcı iştahı ve gerçekçi çıkış varsayımları." },
    ],
    investmentPrepItems: [
      "Bütçe aralığı ve tercih edilen finansman yöntemi",
      "Hedef konum veya pazar alanı",
      "Tercih edilen varlık sınıfı — konut, ticari veya arsa",
      "Yatırım amacı — getiri, sermaye büyümesi veya kendi kullanım",
      "Zaman çizelgesi ve risk toleransı",
    ],
  },
  fa: {
    heroEyebrow: "اطلاعات بازار",
    heroTitle: "دیدگاه‌های املاک و راهنمای سرمایه‌گذاری",
    heroLead:
      "زمینه عملی بازار برای خریداران، سرمایه‌گذاران و توسعه‌دهندگانی که کیفیت موقعیت، سیگنال‌های تقاضا و جایگاه کلاس دارایی را در عُمان، ترکیه و منطقه گسترده‌تر ارزیابی می‌کنند.",
    statAssetClasses: "کلاس دارایی",
    statMarketSignals: "سیگنال بازار",
    statFocusMarkets: "بازار متمرکز",
    statEvaluationSteps: "مرحله ارزیابی",
    panelLabel: "خلاصه بازار",
    panelTitle: "قبل از حرکت، فرصت را بخوانید.",
    panelItems: ["کیفیت موقعیت و دسترسی", "تقاضا، بازده و عمق فروش مجدد", "خط لوله پروژه و زمان‌بندی"],
    panelAria: "خلاصه دیدگاه بازار",
    categoriesEyebrow: "دسته‌های دیدگاه",
    categoriesTitle: "آنچه پوشش می‌دهیم",
    categoriesLead: "زمینه بازار در انواع ملک، موقعیت سرمایه‌گذاری، فعالیت توسعه و شرایط عرضه.",
    marketsEyebrow: "پوشش جغرافیایی",
    marketsTitle: "بازارهایی که فعالانه دنبال می‌کنیم",
    marketsLead:
      "تمرکز ما عُمان، ترکیه، شور همکاری خلیج و سرمایه‌گذاران بین‌المللی مقایسه‌کننده این بازارها را پوشش می‌دهد. هر geography سیگنال، قوانین مالکیت و عوامل زمان‌بندی سرمایه‌گذاری م distinct دارد.",
    stepsEyebrow: "ارزیابی بازار",
    stepsTitle: "چگونه یک فرصت را بخوانیم",
    stepsLead: "چهار عاملی که قبل از پیشنهاد گزینه به خریداران، سرمایه‌گذاران یا توسعه‌دهندگان بررسی می‌شود.",
    signalsEyebrow: "سیگنال‌ها",
    signalsTitle: "سیگنال‌های کلیدی برای رصد",
    signalsLead: "عواملی که کیفیت فرصت و زمان‌بندی سرمایه‌گذاری را در هر منطقه بازار تغییر می‌دهند.",
    prepEyebrow: "آمادگی",
    prepTitle: "آماده بیایید، گزینه‌های بهتری بگیرید",
    prepLead:
      "مشتریانی که جزئیات کلیدی را از ابتدا به اشتراک می‌گذارند، گزینه‌های متمرکز دریافت می‌کنند نه فهرست‌های گسترده. یک خلاصه سرمایه‌گذاری روشن به ما امکان می‌دهد موقعیت، کلاس دارایی و زمان‌بندی را با فرصت‌های واقعی تطبیق دهیم.",
    prepCardLabel: "الگوی خلاصه سرمایه‌گذاری",
    prepCardItems: [
      "بازار: مسقط، ترکیه یا خلیج",
      "دارایی: مسکونی · تجاری · زمین",
      "بودجه: ۵۰ هزار تا ۵۰۰ هزار ریال عمانی",
      "هدف: بازده · رشد سرمایه · استفاده شخصی",
      "زمان: زیر ۶ ماه",
    ],
    prepCardFooter: "یک خلاصه روشن فهرست کوتاه متمرکز می‌دهد — نه جستجوی عمومی.",
    ctaEyebrow: "مرحله بعد",
    ctaTitle: "آماده ارزیابی موقعیت خود هستید؟",
    ctaLead: "موقعیت، کلاس دارایی، محدوده بودجه و هدف سرمایه‌گذاری را به اشتراک بگذارید. با زمینه بازار و گزینه‌های مرتبط بازمی‌گردیم.",
    contactUs: "تماس با ما",
    categories: [
      { iconKey: "Building2", label: "بازارهای املاک", desc: "کلاس‌های دارایی مسکونی، تجاری و سرمایه‌گذاری بر اساس کیفیت موقعیت، عمق تقاضا و زمینه قیمت." },
      { iconKey: "TrendingUp", label: "چشم‌انداز سرمایه‌گذاری", desc: "اهداف بازده، انتظارات دوره نگهداری، مسیرهای خروج و موقعیت سرمایه قبل از فهرست کوتاه." },
      { iconKey: "ClipboardCheck", label: "فعالیت توسعه", desc: "کوریدورهای ساخت فعال، تغییرات کاربری زمین، خط لوله پروژه و تغییرات کاربری اراضی که بر کیفیت فرصت اثر می‌گذارد." },
      { iconKey: "PackageCheck", label: "مصالح و عرضه", desc: "هزینه‌های ورودی ساخت، زمان تأمین، دسترس‌پذیری تأمین و روند قیمت مصالح بر اساس مرحله پروژه." },
    ],
    focusMarkets: [
      { name: "مسقط و عُمان", note: "بازار اصلی برای خریداران بین‌المللی، سرمایه‌گذاران و دارایی‌های متمرکز بر مستاجر در مناطق freehold." },
      { name: "استانبول و ترکیه", note: "فعال برای زمین توسعه، سرمایه‌گذاری مسکونی و پروژه‌های مرتبط با ساخت در کوریدورهای رشد بالا." },
      { name: "منطقه خلیج", note: "فرصت‌های املاک تجاری و سرمایه‌گذاری فرامرزی در بازارهای خلیج و اقتصادهای مرتبط." },
      { name: "مشتریان بین‌المللی", note: "سرمایه‌گذاران پراکنده و فرامرزی که موقعیت عُمان و ترکیه را با معیار بازار محلی مقایسه می‌کنند." },
    ],
    evaluationSteps: [
      { label: "کیفیت موقعیت", desc: "مسیرهای دسترسی، محرک‌های تقاضای اطراف، سرمایه‌گذاری زیرساخت و قدرت حوزه جذب قبل از قیمت‌گذاری بررسی می‌شود." },
      { label: "سیگنال‌های تقاضا", desc: "نرخ اشغال، پروفایل خریدار و مستاجر، سرعت جذب و عمق اجاره در منطقه نزدیک." },
      { label: "زمینه توسعه", desc: "خط لوله پروژه نزدیک، تغییرات زیرساخت برنامه‌ریزی‌شده، فعالیت کاربری اراضی و موقعیت عرضه رقابتی در ۳–۵ سال." },
      { label: "مورد سرمایه‌گذاری", desc: "محدوده بازده، منطق دوره نگهداری، قیمت ورود نسبت به خروج‌های مشابه و تناسب ریسک و بازده برای پروفایل سرمایه‌گذار." },
    ],
    marketSignals: [
      { label: "زیرساخت و دسترسی", desc: "تغییرات توسعه جاده، متro و تأسیسات که ارزش حوزه جذب و تقاضای اجاره را تغییر می‌دهد." },
      { label: "تقاضای مستاجر و خریدار", desc: "سرعت جذب، عمق اشغال، فعالیت نوع خریدار و نرخ vacancy بر اساس کلاس دارایی." },
      { label: "خط لوله توسعه", desc: "حجم عرضه آینده، زمان تکمیل و نحوه رقابت پروژه‌های جدید با موجودی فعلی." },
      { label: "قیمت‌گذاری مشابه", desc: "معیار معاملات واحد و مترمربع و جهت حرکت قیمت." },
      { label: "محیط مقرراتی", desc: "سیاست مالکیت، برنامه‌های مرتبط با ویزا، قوانین سرمایه‌گذاری خارجی و تغییرات برنامه‌ریزی محلی." },
      { label: "خروج و نقدینگی", desc: "عمق فروش مجدد، مدت فروش در بخش هدف، اشتهای خریدار و فرضیات خروج واقع‌بینانه." },
    ],
    investmentPrepItems: [
      "محدوده بودجه و روش تأمین مالی ترجیحی",
      "موقعیت یا منطقه بازار هدف",
      "کلاس دارایی ترجیحی — مسکونی، تجاری یا زمین",
      "هدف سرمایه‌گذاری — بازده، رشد سرمایه یا استفاده شخصی",
      "زمان‌بندی و تحمل ریسک",
    ],
  },
  ar: {
    heroEyebrow: "ذكاء السوق",
    heroTitle: "رؤى العقارات وإرشاد الاستثمار",
    heroLead:
      "سياق سوقي عملي للمشترين والمستثمرين والمطورين الذين يقيّمون جودة الموقع وإشارات الطلب وموقع فئة الأصول في عُمان وتركيا والمنطقة الأوسع.",
    statAssetClasses: "فئات الأصول",
    statMarketSignals: "إشارات السوق",
    statFocusMarkets: "الأسواق المركّزة",
    statEvaluationSteps: "خطوات التقييم",
    panelLabel: "ملخص السوق",
    panelTitle: "اقرأ الفرصة قبل أن تتحرك.",
    panelItems: ["جودة الموقع والوصول", "الطلب والعائد وعمق إعادة البيع", "خط المشاريع والتوقيت"],
    panelAria: "ملخص رؤى السوق",
    categoriesEyebrow: "فئات الرؤى",
    categoriesTitle: "ما نغطيه",
    categoriesLead: "سياق السوق عبر أنواع العقارات ومواقف الاستثمار ونشاط التطوير وظروف العرض.",
    marketsEyebrow: "التغطية الجغرافية",
    marketsTitle: "الأسواق التي نتابعها بنشاط",
    marketsLead:
      "يركز اهتمامنا على عُمان وتركيا ومجلس التعاون والمستثمرين الدوليين الذين يقارنون هذه الأسواق. لكل منطقة إشارات وقواعد ملكية وعوامل توقيت استثمار مميزة.",
    stepsEyebrow: "تقييم السوق",
    stepsTitle: "كيف تقرأ فرصة",
    stepsLead: "العوامل الأربعة التي تُراجع قبل التوصية بخيارات للمشترين أو المستثمرين أو المطورين.",
    signalsEyebrow: "الإشارات",
    signalsTitle: "إشارات رئيسية للمراقبة",
    signalsLead: "العوامل التي تغيّر جودة الفرصة وتوقيت الاستثمار في أي منطقة سوق.",
    prepEyebrow: "الاستعداد",
    prepTitle: "تعال مستعداً، واحصل على خيارات أفضل",
    prepLead:
      "العملاء الذين يشاركون التفاصيل الرئيسية مسبقاً يحصلون على خيارات مركّزة بدلاً من قوائم فئات واسعة. ملخص استثمار واضح يتيح لنا مطابقة الموقع وفئة الأصل والتوقيت مع فرص حقيقية.",
    prepCardLabel: "قالب ملخص الاستثمار",
    prepCardItems: [
      "السوق: مسقط أو تركيا أو الخليج",
      "الأصل: سكني · تجاري · أرض",
      "الميزانية: 50K – 500K ريال عماني",
      "الغرض: عائد · نمو رأسمالي · استخدام شخصي",
      "الجدول: أقل من 6 أشهر",
    ],
    prepCardFooter: "ملخص واضح يعطي قائمة قصيرة مركّزة — وليس بحثاً عاماً.",
    ctaEyebrow: "الخطوة التالية",
    ctaTitle: "هل أنت مستعد لتقييم موقفك؟",
    ctaLead: "شارك الموقع وفئة الأصل ونطاق الميزانية والغرض الاستثماري. سنعود بسياق السوق والخيارات ذات الصلة.",
    contactUs: "تواصل معنا",
    categories: [
      { iconKey: "Building2", label: "أسواق العقارات", desc: "فئات الأصول السكنية والتجارية والاستثمارية تُراجع حسب جودة الموقع وعمق الطلب وسياق التسعير." },
      { iconKey: "TrendingUp", label: "مشهد الاستثمار", desc: "أهداف العائد وتوقعات فترة الاحتفاظ ومسارات الخروج وموقع رأس المال قبل اختصار القائمة." },
      { iconKey: "ClipboardCheck", label: "نشاط التطوير", desc: "ممرات البناء النشطة وتغييرات استخدام الأرض وخط المشاريع وتغييرات تقسيم المناطق التي تؤثر على جودة الفرصة." },
      { iconKey: "PackageCheck", label: "المواد والعرض", desc: "تكاليف مدخلات البناء وأوقات التوريد وتوفر المشتريات واتجاهات أسعار المواد حسب مرحلة المشروع." },
    ],
    focusMarkets: [
      { name: "مسقط وعُمان", note: "السوق الرئيسي للمشترين الدوليين والمستثمرين والأصول الموجهة للمستأجرين في مناطق التملك الحر." },
      { name: "إسطنbul وتركيا", note: "نشط لأرض التطوير والاستثمار السكني والمشاريع المرتبطة بالبناء في ممرات النمو العالي." },
      { name: "منطقة الخليج", note: "فرص عقارية تجارية واستثمارية عبر الحدود في أسواق الخليج والاقتصادات المرتبطة." },
      { name: "عملاء دوليون", note: "مستثمرون من الشتات وعبر الحدود يقارنون موقع عُمان وتركيا بمعايير السوق المحلي." },
    ],
    evaluationSteps: [
      { label: "جودة الموقع", desc: "مسارات الوصول ومحركات الطلب المحيطة والاستثمار في البنية التحتية وقوة catchment تُراجع قبل التسعير." },
      { label: "إشارات الطلب", desc: "معدلات الإشغال وملف المشتري والمستأجر وسرعة الامتصاص وعمق الإيجار comparable في المنطقة الم immediate." },
      { label: "سياق التطوير", desc: "خط المشاريع القريب وتغييرات البنية التحتية الم planned ونشاط الت zoning وموقع العرض التنافسي على 3–5 سنوات." },
      { label: "حالة الاستثمار", desc: "نطاق العائد ومنطق فترة الاحتفاظ وسعر الدخول مقارنة بالخروجات comparable وملاءمة المخاطر والعائد لملف المستثمر." },
    ],
    marketSignals: [
      { label: "البنية التحتية والوصول", desc: "تحولات تطوير الطرق والمتro والمرافق التي تغيّر قيمة catchment وطلب الإيجار." },
      { label: "طلب المستأجر والمشتري", desc: "سرعة الامتصاص وعمق الإشغال ونشاط نوع المشتري وvacancy comparable حسب فئة الأصل." },
      { label: "خط التطوير", desc: "حجم العرض القادم وتوقيت الإنجاز وكيف تنافس المشاريع الجديدة الم stock الحالي." },
      { label: "تسعير comparable", desc: "معايير المعاملات per-unit وper-square-meter واتجاه حركة الأسعار." },
      { label: "البيئة التنظيمية", desc: "سياسة الملكية وبرامج مرتبطة بالvisa وقواعد الاستثمار الأجنبي وتغييرات التخطيط المحلي." },
      { label: "الخروج والسيولة", desc: "عمق إعادة البيع وdays-to-sale في الش segment المستهدف وappetite المشتري وافتراضات خروج واقعية." },
    ],
    investmentPrepItems: [
      "نطاق الميزانية وطريقة التمويل المفضلة",
      "الموقع أو منطقة السوق المستهدفة",
      "فئة الأصل المفضلة — سكني أو تجاري أو أرض",
      "غرض الاستثمار — عائد أو نمو رأسمالي أو استخدام شخصي",
      "الجدول الزمني وتحمل المخاطر",
    ],
  },
};

export function getInsightsPageCopy(lang) {
  return insightsPageCopy[lang] || insightsPageCopy.en;
}
