const categoriesEn = [
  { iconKey: "Building2", label: "Concrete & Cement", desc: "Ready-mix concrete, cement grades, admixtures, and reinforcement products for foundations, slabs, columns, and structural elements." },
  { iconKey: "Layers", label: "Steel & Rebar", desc: "Structural steel sections, reinforcing bar, mesh, and fabricated steel components for concrete and frame construction projects." },
  { iconKey: "Home", label: "Blocks & Bricks", desc: "Hollow and solid blocks, clay bricks, lightweight partition blocks, and masonry units for wall systems and partitions." },
  { iconKey: "Zap", label: "Electrical Materials", desc: "Cabling, conduit, switchgear, distribution boards, and finishing accessories for residential and commercial electrical installations." },
  { iconKey: "Droplet", label: "Plumbing Materials", desc: "UPVC and PPR piping, fittings, valves, sanitary connections, and drainage systems for project-specific layouts and delivery." },
  { iconKey: "FileText", label: "Finishing Materials", desc: "Tiles, paints, plaster, gypsum board, flooring systems, and cladding materials for interior and exterior finishing work." },
];

const processStepsEn = [
  { label: "Requirement Collection", desc: "Categories, quantities, specifications, and delivery details collected upfront to shape a clear request." },
  { label: "Supplier Matching", desc: "Qualified suppliers matched to your specification, project location, and delivery urgency." },
  { label: "Quotation Review", desc: "Quotations organized by grade, price, lead time, and availability so comparison is straightforward." },
  { label: "Delivery Coordination", desc: "Delivery schedules aligned to site readiness, construction sequence, and phased project timelines." },
  { label: "Project Follow-up", desc: "Order status, delivery confirmation, and quality checks tracked and communicated through completion." },
];

const supplyAreasEn = [
  { iconKey: "Home", label: "Residential Projects", desc: "Material sourcing for villas, apartments, and housing developments — from foundation through finishing stage.", tags: ["Concrete", "Steel", "Finishing", "MEP"] },
  { iconKey: "Building2", label: "Commercial Buildings", desc: "Supply coordination for retail, office, and mixed-use projects with multi-trade material requirements and phased delivery.", tags: ["Structural", "Cladding", "Electrical", "Plumbing"] },
  { iconKey: "PackageCheck", label: "Industrial Facilities", desc: "Heavy-duty materials and industrial-grade supply for warehouses, factories, and logistics facilities across the region.", tags: ["Steel", "Roofing", "Concrete", "Industrial"] },
  { iconKey: "MapPin", label: "Infrastructure Projects", desc: "Civil and infrastructure materials for roads, utilities, landscaping, and public works projects with bulk sourcing support.", tags: ["Aggregates", "Pipes", "Civil", "Drainage"] },
];

const trustIndicatorsEn = [
  { iconKey: "BadgeCheck", label: "Verified Suppliers", desc: "Material sources are checked for reliability, quality consistency, and delivery capacity before engagement." },
  { iconKey: "FileText", label: "Clear Quotations", desc: "Quotes are organized by grade, availability, pricing, and lead time to simplify comparison and decision-making." },
  { iconKey: "ClipboardCheck", label: "Specification Matching", desc: "Material specifications are matched to project drawings, grade requirements, and acceptable alternatives." },
  { iconKey: "Truck", label: "Delivery Planning", desc: "Delivery timelines are tied to site schedules and phased delivery is coordinated to reduce site congestion." },
  { iconKey: "TrendingUp", label: "Progress Tracking", desc: "Order status and delivery milestones are tracked and communicated from confirmation to site arrival." },
  { iconKey: "Globe", label: "International Sourcing", desc: "Access to suppliers across Oman, Turkey, and international markets for specialized or bulk material needs." },
];

export const materialsPageCopy = {
  en: {
    heroEyebrow: "Building Materials",
    heroTitle: "Building material supply, sourced with project context.",
    heroLead:
      "Structured sourcing for concrete, steel, blocks, MEP, plumbing, and finishing materials with supplier coordination, quotation review, and delivery planning.",
    statCategories: "Material Categories",
    statSteps: "Coordination Steps",
    statProjectTypes: "Project Types",
    infoCardLabel: "Supply Coordination",
    infoCardItems: ["Specification review", "Supplier matching", "Delivery planning", "Order follow-up"],
    categoriesEyebrow: "What We Source",
    categoriesTitle: "Material categories",
    categoriesLead: "Core construction and finishing materials sourced, specified, and coordinated for your project requirements.",
    processEyebrow: "Our Process",
    processTitle: "How we support projects",
    processLead: "A structured path from initial requirement to delivery confirmation — keeping every stage clear and on track.",
    areasEyebrow: "Project Types",
    areasTitle: "Featured supply areas",
    areasLead: "Material sourcing and coordination support tailored for different project types and scales.",
    trustEyebrow: "Why Choose Us",
    trustTitle: "Why work with us",
    trustLead:
      "We connect construction projects with reliable material sources, manage supplier communication, and keep delivery timelines tied to actual site needs.",
    ctaEyebrow: "Next Step",
    ctaTitle: "Need material sourcing support?",
    ctaLead:
      "Share your material list, project type, quantities, delivery location, and timeline. We will match suppliers and coordinate the next steps.",
    contactUs: "Contact us",
    categories: categoriesEn,
    processSteps: processStepsEn,
    supplyAreas: supplyAreasEn,
    trustIndicators: trustIndicatorsEn,
  },
  tr: {
    heroEyebrow: "Yapı Malzemeleri",
    heroTitle: "Projenize göre tedarik edilen yapı malzemeleri",
    heroLead:
      "Beton, çelik, blok, mekanik-elektrik-tesisat ve ince işler için tedarikçi koordinasyonu, fiyat teklifi incelemesi ve teslimat planlaması.",
    statCategories: "Malzeme Kategorisi",
    statSteps: "Koordinasyon Adımı",
    statProjectTypes: "Proje Türü",
    infoCardLabel: "Tedarik Koordinasyonu",
    infoCardItems: ["Spesifikasyon incelemesi", "Tedarikçi eşleştirme", "Teslimat planlaması", "Sipariş takibi"],
    categoriesEyebrow: "Tedarik Ettiğimiz",
    categoriesTitle: "Malzeme kategorileri",
    categoriesLead: "Projenizin gereksinimine göre belirlenen, tedarik edilen ve koordine edilen temel inşaat ve ince iş malzemeleri.",
    processEyebrow: "Sürecimiz",
    processTitle: "Projeleri nasıl destekliyoruz",
    processLead: "İlk gereksinimden teslimat onayına kadar yapılandırılmış bir yol — her aşamayı net ve takipte tutar.",
    areasEyebrow: "Proje Türleri",
    areasTitle: "Öne çıkan tedarik alanları",
    areasLead: "Farklı proje türleri ve ölçekleri için uyarlanmış malzeme tedarik ve koordinasyon desteği.",
    trustEyebrow: "Neden Biz",
    trustTitle: "Neden bizimle çalışmalısınız",
    trustLead:
      "İnşaat projelerini güvenilir malzeme kaynaklarıyla buluşturur, tedarikçi iletişimini yönetir ve teslimat zaman çizelgelerini gerçek saha ihtiyaçlarına bağlarız.",
    ctaEyebrow: "Sonraki Adım",
    ctaTitle: "Malzeme tedarik desteğine mi ihtiyacınız var?",
    ctaLead:
      "Malzeme listenizi, proje türünüzü, miktarları, teslimat konumunu ve zaman çizelgesini paylaşın. Tedarikçileri eşleştirip sonraki adımları koordine edelim.",
    contactUs: "Bize ulaşın",
    categories: [
      { iconKey: "Building2", label: "Beton ve Çimento", desc: "Temeller, döşemeler, kolonlar ve taşıyıcı elemanlar için hazır beton, çimento sınıfları, katkılar ve donatı ürünleri." },
      { iconKey: "Layers", label: "Çelik ve Nervürlü Demir", desc: "Betonarme ve çerçeve inşaat projeleri için yapısal çelik profiller, nervürlü demir, hasır ve imalat çelik bileşenleri." },
      { iconKey: "Home", label: "Blok ve Tuğla", desc: "Duvar sistemleri ve bölme duvarları için boş ve dolu bloklar, kil tuğlalar, hafif bölme blokları ve duvar elemanları." },
      { iconKey: "Zap", label: "Elektrik Malzemeleri", desc: "Konut ve ticari elektrik tesisatları için kablo, kanal, şalt, pano ve bitirme aksesuarları." },
      { iconKey: "Droplet", label: "Tesisat Malzemeleri", desc: "Proje özel düzenler ve teslimat için UPVC ve PPR boru, bağlantı parçaları, vanalar, sıhhi bağlantılar ve drenaj sistemleri." },
      { iconKey: "FileText", label: "İnce İş Malzemeleri", desc: "İç ve dış ince iş aşaması için fayans, boya, sıva, alçıpan, zemin sistemleri ve cephe kaplama malzemeleri." },
    ],
    processSteps: [
      { label: "Gereksinim Toplama", desc: "Kategoriler, miktarlar, spesifikasyonlar ve teslimat detayları net bir talep oluşturmak için baştan toplanır." },
      { label: "Tedarikçi Eşleştirme", desc: "Nitelikli tedarikçiler spesifikasyonunuza, proje konumunuza ve teslimat aciliyetinize göre eşleştirilir." },
      { label: "Teklif İncelemesi", desc: "Teklifler sınıf, fiyat, teslim süresi ve uygunluğa göre düzenlenir; karşılaştırma kolaylaşır." },
      { label: "Teslimat Koordinasyonu", desc: "Teslimat programları saha hazırlığı, inşaat sırası ve aşamalı proje zaman çizelgelerine göre hizalanır." },
      { label: "Proje Takibi", desc: "Sipariş durumu, teslimat onayı ve kalite kontrolleri tamamlanana kadar takip edilir ve iletilir." },
    ],
    supplyAreas: [
      { iconKey: "Home", label: "Konut Projeleri", desc: "Villa, daire ve konut projeleri için temelden ince iş aşamasına kadar malzeme tedariki.", tags: ["Beton", "Çelik", "İnce iş", "MEP"] },
      { iconKey: "Building2", label: "Ticari Binalar", desc: "Perakende, ofis ve karma kullanım projeleri için çok disiplinli malzeme gereksinimleri ve aşamalı teslimat.", tags: ["Yapısal", "Kaplama", "Elektrik", "Tesisat"] },
      { iconKey: "PackageCheck", label: "Endüstriyel Tesisler", desc: "Depo, fabrika ve lojistik tesisleri için ağır hizmet malzemeleri ve endüstriyel tedarik.", tags: ["Çelik", "Çatı", "Beton", "Endüstriyel"] },
      { iconKey: "MapPin", label: "Altyapı Projeleri", desc: "Yol, altyapı, peyzaj ve kamu projeleri için toplu tedarik destekli sivil malzemeler.", tags: ["Agrega", "Boru", "Sivil", "Drenaj"] },
    ],
    trustIndicators: [
      { iconKey: "BadgeCheck", label: "Doğrulanmış Tedarikçiler", desc: "Malzeme kaynakları güvenilirlik, kalite tutarlılığı ve teslimat kapasitesi açısından kontrol edilir." },
      { iconKey: "FileText", label: "Net Teklifler", desc: "Teklifler sınıf, uygunluk, fiyat ve teslim süresine göre düzenlenir; karar vermeyi kolaylaştırır." },
      { iconKey: "ClipboardCheck", label: "Spesifikasyon Eşleştirme", desc: "Malzeme spesifikasyonları proje çizimleri, sınıf gereksinimleri ve kabul edilebilir alternatiflerle eşleştirilir." },
      { iconKey: "Truck", label: "Teslimat Planlaması", desc: "Teslimat zaman çizelgeleri saha programlarına bağlanır; aşamalı teslimat koordine edilir." },
      { iconKey: "TrendingUp", label: "İlerleme Takibi", desc: "Sipariş durumu ve teslimat kilometre taşları onaydan saha varışına kadar takip edilir." },
      { iconKey: "Globe", label: "Uluslararası Tedarik", desc: "Umman, Türkiye ve uluslararası pazarlarda özel veya toplu malzeme ihtiyaçları için tedarikçi erişimi." },
    ],
  },
  fa: {
    heroEyebrow: "مصالح ساختمانی",
    heroTitle: "تأمین مصالح ساختمانی با زمینه پروژه.",
    heroLead:
      "تأمین ساختاریافته بتن، فولاد، بلوک، MEP، لوله‌کشی و مصالح نازک‌کاری با هماهنگی تأمین‌کننده، بررسی پیش‌فاکتور و برنامه‌ریزی تحویل.",
    statCategories: "دسته مصالح",
    statSteps: "مرحله هماهنگی",
    statProjectTypes: "نوع پروژه",
    infoCardLabel: "هماهنگی تأمین",
    infoCardItems: ["بررسی مشخصات", "تطبیق تأمین‌کننده", "برنامه‌ریزی تحویل", "پیگیری سفارش"],
    categoriesEyebrow: "آنچه تأمین می‌کنیم",
    categoriesTitle: "دسته‌بندی مصالح",
    categoriesLead: "مصالح اصلی ساخت و نازک‌کاری که برای نیازهای پروژه شما تأمین، مشخص و هماهنگ می‌شوند.",
    processEyebrow: "فرایند ما",
    processTitle: "چگونه از پروژه‌ها پشتیبانی می‌کنیم",
    processLead: "مسیر ساختاریافته از نیاز اولیه تا تأیید تحویل — هر مرحله را شفاف و در مسیر نگه می‌دارد.",
    areasEyebrow: "انواع پروژه",
    areasTitle: "حوزه‌های تأمین برجسته",
    areasLead: "پشتیبانی تأمین و هماهنگی مصالح متناسب با انواع و مقیاس‌های مختلف پروژه.",
    trustEyebrow: "چرا ما",
    trustTitle: "چرا با ما کار کنید",
    trustLead:
      "پروژه‌های ساخت را به منابع مطمئن مصالح متصل می‌کنیم، ارتباط با تأمین‌کنندگان را مدیریت می‌کنیم و زمان‌بندی تحویل را به نیاز واقعی سایت گره می‌زنیم.",
    ctaEyebrow: "مرحله بعد",
    ctaTitle: "به پشتیبانی تأمین مصالح نیاز دارید؟",
    ctaLead:
      "لیست مصالح، نوع پروژه، مقادیر، محل تحویل و زمان‌بندی را ارسال کنید. تأمین‌کنندگان را تطبیق داده و گام‌های بعدی را هماهنگ می‌کنیم.",
    contactUs: "تماس با ما",
    categories: [
      { iconKey: "Building2", label: "بتن و سیمان", desc: "بتن آماده، درجه سیمان، افزودنی‌ها و محصولات تقویتی برای فونداسیون، دال، ستون و عناصر سازه‌ای." },
      { iconKey: "Layers", label: "فولاد و میلگرد", desc: "پروفیل‌های فولادی سازه‌ای، میلگرد، مش و اجزای فولادی ساخت برای پروژه‌های بتنی و اسکلت فلزی." },
      { iconKey: "Home", label: "بلوک و آجر", desc: "بلوک توخالی و توپر، آجر رس، بلوک سبک پارتیشن و واحدهای بنایی برای دیوار و پارتیشن." },
      { iconKey: "Zap", label: "مصالح برقی", desc: "کابل، کانال (داکت)، کلیدها، تابلوهای توزیع و لوازم نهایی برای تأسیسات برقی مسکونی و تجاری." },
      { iconKey: "Droplet", label: "مصالح لوله‌کشی", desc: "لوله UPVC و PPR، اتصالات، شیر، اتصالات بهداشتی و سیستم‌های زهکشی برای چیدمان و تحویل پروژه." },
      { iconKey: "FileText", label: "مصالح نازک‌کاری", desc: "کاشی، رنگ، گچ، گچ‌برگ، کف‌پوش و مصالح نما برای کارهای داخلی و خارجی." },
    ],
    processSteps: [
      { label: "جمع‌آوری نیاز", desc: "دسته‌ها، مقادیر، مشخصات و جزئیات تحویل از ابتدا برای شکل‌دهی درخواست روشن جمع‌آوری می‌شود." },
      { label: "تطبیق تأمین‌کننده", desc: "تأمین‌کنندگان واجد شرایط با مشخصات، موقعیت پروژه و فوریت تحویل شما تطبیق داده می‌شوند." },
      { label: "بررسی پیش‌فاکتور", desc: "پیش‌فاکتورها بر اساس درجه، قیمت، زمان تحویل و موجودی مرتب می‌شوند تا مقایسه آسان باشد." },
      { label: "هماهنگی تحویل", desc: "برنامه تحویل با آمادگی سایت، توالی ساخت و زمان‌بندی مرحله‌ای پروژه هم‌راستا می‌شود." },
      { label: "پیگیری پروژه", desc: "وضعیت سفارش، تأیید تحویل و کنترل کیفیت تا تکمیل پیگیری و اطلاع‌رسانی می‌شود." },
    ],
    supplyAreas: [
      { iconKey: "Home", label: "پروژه‌های مسکونی", desc: "تأمین مصالح برای ویلا، آپارتمان و پروژه‌های مسکونی — از فونداسیون تا نازک‌کاری.", tags: ["بتن", "فولاد", "نازک‌کاری", "MEP"] },
      { iconKey: "Building2", label: "ساختمان‌های تجاری", desc: "هماهنگی تأمین برای پروژه‌های خرده‌فروشی، اداری و مختلط با نیاز چند رشته‌ای و تحویل مرحله‌ای.", tags: ["سازه", "نما", "برق", "لوله‌کشی"] },
      { iconKey: "PackageCheck", label: "تأسیسات صنعتی", desc: "مصالح سنگین و تأمین درجه صنعتی برای انبار، کارخانه و تأسیسات لجستیک در منطقه.", tags: ["فولاد", "سقف", "بتن", "صنعتی"] },
      { iconKey: "MapPin", label: "پروژه‌های زیرساخت", desc: "مصالح عمرانی و زیرساختی برای جاده، تأسیسات، فضای سبز و پروژه‌های عمومی با تأمین عمده.", tags: ["سنگدانه", "لوله", "عمران", "زهکشی"] },
    ],
    trustIndicators: [
      { iconKey: "BadgeCheck", label: "تأمین‌کنندگان تأییدشده", desc: "منابع مصالح از نظر قابلیت اطمینان، ثبات کیفیت و ظرفیت تحویل قبل از همکاری بررسی می‌شوند." },
      { iconKey: "FileText", label: "پیش‌فاکتور شفاف", desc: "پیش‌فاکتورها بر اساس درجه، موجودی، قیمت و زمان تحویل مرتب می‌شوند." },
      { iconKey: "ClipboardCheck", label: "تطبیق مشخصات", desc: "مشخصات مصالح با نقشه پروژه، درجه مورد نیاز و جایگزین‌های قابل قبول تطبیق داده می‌شود." },
      { iconKey: "Truck", label: "برنامه‌ریزی تحویل", desc: "زمان‌بندی تحویل به برنامه سایت گره خورده و تحویل مرحله‌ای هماهنگ می‌شود." },
      { iconKey: "TrendingUp", label: "پیگیری پیشرفت", desc: "وضعیت سفارش و نقاط عطف تحویل از تأیید تا رسیدن به سایت پیگیری می‌شود." },
      { iconKey: "Globe", label: "تأمین بین‌المللی", desc: "دسترسی به تأمین‌کنندگان در عُمان، ترکیه و بازارهای بین‌المللی برای نیازهای تخصصی یا عمده." },
    ],
  },
  ar: {
    heroEyebrow: "مواد البناء",
    heroTitle: "توريد مواد البناء مع سياق المشروع.",
    heroLead:
      "توريد منظم للخرسانة والفولاذ والبلوك وMEP والسباكة ومواد التشطيب مع تنسيق الموردين ومراجعة العروض وتخطيط التسليم.",
    statCategories: "فئات المواد",
    statSteps: "خطوات التنسيق",
    statProjectTypes: "أنواع المشاريع",
    infoCardLabel: "تنسيق التوريد",
    infoCardItems: ["مراجعة المواصفات", "مطابقة الموردين", "تخطيط التسليم", "متابعة الطلب"],
    categoriesEyebrow: "ما نوفره",
    categoriesTitle: "فئات المواد",
    categoriesLead: "مواد البناء والتشطيب الأساسية التي يتم توريدها وتحديدها وتنسيقها وفق متطلبات مشروعك.",
    processEyebrow: "عمليتنا",
    processTitle: "كيف ندعم المشاريع",
    processLead: "مسار منظم من المتطلب الأولي إلى تأكيد التسليم — يبقي كل مرحلة واضحة وعلى المسار.",
    areasEyebrow: "أنواع المشاريع",
    areasTitle: "مجالات التوريد المميزة",
    areasLead: "دعم توريد وتنسيق المواد مصمم لأنواع ومقاييس مشاريع مختلفة.",
    trustEyebrow: "لماذا نحن",
    trustTitle: "لماذا العمل معنا",
    trustLead:
      "نربط مشاريع البناء بمصادر مواد موثوقة، وندير التواصل مع الموردين، ونربط جداول التسليم باحتياجات الموقع الفعلية.",
    ctaEyebrow: "الخطوة التالية",
    ctaTitle: "هل تحتاج دعم توريد المواد؟",
    ctaLead:
      "شارك قائمة المواد ونوع المشروع والكميات وموقع التسليم والجدول الزمني. سنطابق الموردين وننسق الخطوات التالية.",
    contactUs: "تواصل معنا",
    categories: [
      { iconKey: "Building2", label: "الخرسانة والأسمنت", desc: "خرسانة جاهزة، درجات الأسمنت، المضافات ومنتجات التسليح للأساسات والبلاطات والأعمدة والعناصر الإنشائية." },
      { iconKey: "Layers", label: "الفولاذ وحديد التسليح", desc: "مقاطع فولاذية إنشائية، حديد تسليح، شبك ومكونات فولاذية للمشاريع الخرسانية والإطارية." },
      { iconKey: "Home", label: "البلوك والطوب", desc: "بلوك مجوف ومصمت، طوب طيني، بلوك تقسيم خفيف ووحدات بناء للجدران والفواصل." },
      { iconKey: "Zap", label: "مواد كهربائية", desc: "كابلات، قنوات، لوحات توزيع وملحقات تشطيب للتركيبات الكهربائية السكنية والتجارية." },
      { iconKey: "Droplet", label: "مواد السباكة", desc: "أنابيب UPVC وPPR، وصلات، صمامات، توصيلات صحية وأنظمة صرف للمخططات والتسليم الخاص بالمشروع." },
      { iconKey: "FileText", label: "مواد التشطيب", desc: "بلاط، دهان، جبس، ألواح جبسية، أرضيات ومواد كسوة الواجهات للأعمال الداخلية والخارجية." },
    ],
    processSteps: [
      { label: "جمع المتطلبات", desc: "تُجمع الفئات والكميات والمواصفات وتفاصيل التسليم مسبقاً لتشكيل طلب واضح." },
      { label: "مطابقة الموردين", desc: "يُطابق الموردون المؤهلون مع مواصفاتك وموقع المشروع وإلحاح التسليم." },
      { label: "مراجعة العروض", desc: "تُنظم العروض حسب الدرجة والسعر ووقت التسليم والتوفر لتسهيل المقارنة." },
      { label: "تنسيق التسليم", desc: "تُوائم جداول التسليم مع جاهزية الموقع وتسلسل البناء والجداول المرحلية." },
      { label: "متابعة المشروع", desc: "تُتابع حالة الطلب وتأكيد التسليم وفحوصات الجودة حتى الاكتمال." },
    ],
    supplyAreas: [
      { iconKey: "Home", label: "مشاريع سكنية", desc: "توريد مواد للفلل والشقق والتطويرات السكنية — من الأساس حتى التشطيب.", tags: ["خرسانة", "فولاذ", "تشطيب", "MEP"] },
      { iconKey: "Building2", label: "مباني تجارية", desc: "تنسيق التوريد لمشاريع التجزئة والمكاتب والاستخدام المختلط بمتطلبات متعددة وتسليم مرحلي.", tags: ["إنشائي", "واجهات", "كهرباء", "سباكة"] },
      { iconKey: "PackageCheck", label: "منشآت صناعية", desc: "مواد ثقيلة وتوريد صناعي للمستودعات والمصانع ومرافق لوجستية في المنطقة.", tags: ["فولاذ", "أسقف", "خرسانة", "صناعي"] },
      { iconKey: "MapPin", label: "مشاريع البنية التحتية", desc: "مواد مدنية وبنية تحتية للطرق والمرافق والتنسيق والأعمال العامة مع دعم التوريد بالجملة.", tags: ["ركام", "أنابيب", "مدني", "صرف"] },
    ],
    trustIndicators: [
      { iconKey: "BadgeCheck", label: "موردون موثقون", desc: "تُفحص مصادر المواد من حيث الموثوقية واتساق الجودة وقدرة التسليم قبل التعاقد." },
      { iconKey: "FileText", label: "عروض واضحة", desc: "تُنظم العروض حسب الدرجة والتوفر والسعر ووقت التسليم." },
      { iconKey: "ClipboardCheck", label: "مطابقة المواصفات", desc: "تُطابق مواصفات المواد مع مخططات المشروع ومتطلبات الدرجة والبدائل المقبولة." },
      { iconKey: "Truck", label: "تخطيط التسليم", desc: "تُربط جداول التسليم بجداول الموقع ويُنسق التسليم المرحلي." },
      { iconKey: "TrendingUp", label: "تتبع التقدم", desc: "تُتابع حالة الطلب ومعالم التسليم من التأكيد حتى وصول الموقع." },
      { iconKey: "Globe", label: "توريد دولي", desc: "الوصول إلى موردين في عُمان وتركيا والأسواق الدولية للاحتياجات المتخصصة أو بالجملة." },
    ],
  },
};

export function getMaterialsPageCopy(lang) {
  return materialsPageCopy[lang] || materialsPageCopy.en;
}
