export const projectsPageCopy = {
  en: {
    heroEyebrow: "Project portfolio",
    heroTitle: "Real Estate, Construction & Development Projects",
    heroLead:
      "Explore selected projects, acquisitions, construction coordination, and building-material initiatives supported by REZAEI GLOBAL LLC.",
    heroSecondary:
      "A focused view of active, completed, and featured work across the group, organized for clients, partners, and serious project conversations.",
    statsAria: "Projects overview",
    statSelectedProjects: "Selected projects",
    statBusinessAreas: "Business areas",
    statCoordinatedGroup: "Coordinated group",
    coverageAria: "Project coverage",
    coverageLabel: "Project coverage",
    coverageTitle: "Selected portfolio routes",
    coverageItems: [
      "Property acquisition support",
      "Construction coordination",
      "Building materials supply",
      "Residency and business support",
    ],
    viewProjects: "View projects",
    gridEyebrow: "Selected work",
    gridTitle: "Project portfolio",
    gridLead: "Browse current and representative projects by business area, status, and next-step relevance.",
    viewProject: "View project",
    ctaTitle: "Have a project or business opportunity to discuss?",
    ctaLead: "Contact REZAEI GLOBAL LLC to discuss partnerships, project coordination, or business support.",
    contactUs: "Contact us",
    area: "Area",
    completionYear: "Completion year",
    projectCategory: "Project category",
    projectOverview: "Project overview",
    projectSetting: "Project setting",
    developmentFocus: "Development focus",
    rezaeiRole: "REZAEI role",
    gallery: "Gallery",
    projectVisuals: "Project visuals",
    viewImage: "View image",
    projectFacts: "Project facts",
    keyInformation: "Key information",
    location: "Location",
    projectType: "Project type",
    status: "Status",
    developmentType: "Development type",
    market: "Market",
    scopeEyebrow: "Scope of involvement",
    scopeTitle: "REZAEI contribution",
    relatedEyebrow: "Related projects",
    relatedTitle: "Explore similar work",
    detailCtaTitle: "Interested in a similar project?",
    detailCtaLead:
      "Speak with REZAEI GLOBAL LLC about property development, construction coordination, acquisition support, or procurement planning.",
    exploreProjects: "Explore projects",
    projectGallery: "Project gallery",
    closeGallery: "Close gallery",
    previousImage: "Previous image",
    nextImage: "Next image",
    galleryAria: (title) => `${title} gallery`,
    openGalleryImage: (title, index) => `Open ${title} gallery image ${index}`,
    showGalleryImage: (index) => `Show gallery image ${index}`,
    viewProjectAria: (title) => `View ${title}`,
    defaultProjectArea: "Project area",
    defaultLocation: "Muscat, Oman",
    defaultMarket: "Oman",
  },
  tr: {
    heroEyebrow: "Proje portföyü",
    heroTitle: "Gayrimenkul, İnşaat ve Geliştirme Projeleri",
    heroLead:
      "REZAEI GLOBAL LLC tarafından desteklenen seçilmiş projeleri, edinimleri, inşaat koordinasyonunu ve yapı malzemesi girişimlerini keşfedin.",
    heroSecondary:
      "Grup genelinde aktif, tamamlanmış ve öne çıkan işlerin odaklı bir görünümü; müşteriler, ortaklar ve ciddi proje görüşmeleri için düzenlenmiştir.",
    statsAria: "Proje özeti",
    statSelectedProjects: "Seçilmiş proje",
    statBusinessAreas: "İş alanı",
    statCoordinatedGroup: "Koordineli grup",
    coverageAria: "Proje kapsamı",
    coverageLabel: "Proje kapsamı",
    coverageTitle: "Seçilmiş portföy rotaları",
    coverageItems: [
      "Gayrimenkul edinim desteği",
      "İnşaat koordinasyonu",
      "Yapı malzemesi tedariki",
      "Oturum ve iş desteği",
    ],
    viewProjects: "Projeleri gör",
    gridEyebrow: "Seçilmiş çalışmalar",
    gridTitle: "Proje portföyü",
    gridLead: "Mevcut ve temsili projelere iş alanı, durum ve sonraki adım uygunluğuna göre göz atın.",
    viewProject: "Projeyi gör",
    ctaTitle: "Tartışılacak bir proje veya iş fırsatınız mı var?",
    ctaLead: "Ortaklıklar, proje koordinasyonu veya iş desteği için REZAEI GLOBAL LLC ile iletişime geçin.",
    contactUs: "Bize ulaşın",
    area: "Alan",
    completionYear: "Tamamlanma yılı",
    projectCategory: "Proje kategorisi",
    projectOverview: "Proje özeti",
    projectSetting: "Proje konumu",
    developmentFocus: "Geliştirme odağı",
    rezaeiRole: "REZAEI rolü",
    gallery: "Galeri",
    projectVisuals: "Proje görselleri",
    viewImage: "Görseli gör",
    projectFacts: "Proje bilgileri",
    keyInformation: "Temel bilgiler",
    location: "Konum",
    projectType: "Proje türü",
    status: "Durum",
    developmentType: "Geliştirme türü",
    market: "Pazar",
    scopeEyebrow: "Katılım kapsamı",
    scopeTitle: "REZAEI katkısı",
    relatedEyebrow: "İlgili projeler",
    relatedTitle: "Benzer çalışmaları keşfedin",
    detailCtaTitle: "Benzer bir projeyle mi ilgileniyorsunuz?",
    detailCtaLead:
      "Gayrimenkul geliştirme, inşaat koordinasyonu, edinim desteği veya tedarik planlaması hakkında REZAEI GLOBAL LLC ile görüşün.",
    exploreProjects: "Projeleri keşfet",
    projectGallery: "Proje galerisi",
    closeGallery: "Galeriyi kapat",
    previousImage: "Önceki görsel",
    nextImage: "Sonraki görsel",
    galleryAria: (title) => `${title} galerisi`,
    openGalleryImage: (title, index) => `${title} galeri görseli ${index} aç`,
    showGalleryImage: (index) => `Galeri görseli ${index} göster`,
    viewProjectAria: (title) => `${title} görüntüle`,
    defaultProjectArea: "Proje alanı",
    defaultLocation: "Maskat, Umman",
    defaultMarket: "Umman",
  },
  fa: {
    heroEyebrow: "پورتفوی پروژه",
    heroTitle: "پروژه‌های املاک، ساخت‌وساز و توسعه",
    heroLead:
      "پروژه‌های منتخب، خرید ملک، هماهنگی ساخت‌وساز و ابتکارات مصالح ساختمانی که توسط REZAEI GLOBAL LLC پشتیبانی می‌شوند را کاوش کنید.",
    heroSecondary:
      "نمای متمرکزی از کارهای فعال، تکمیل‌شده و ویژه در سراسر گروه، برای مشتریان، شرکا و گفتگوهای جدی پروژه سازمان‌دهی شده است.",
    statsAria: "نمای کلی پروژه‌ها",
    statSelectedProjects: "پروژه منتخب",
    statBusinessAreas: "حوزه کسب‌وکار",
    statCoordinatedGroup: "گروه هماهنگ",
    coverageAria: "پوشش پروژه",
    coverageLabel: "پوشش پروژه",
    coverageTitle: "مسیرهای منتخب پورتفوی",
    coverageItems: [
      "پشتیبانی خرید ملک",
      "هماهنگی ساخت‌وساز",
      "تأمین مصالح ساختمانی",
      "پشتیبانی اقامت و کسب‌وکار",
    ],
    viewProjects: "مشاهده پروژه‌ها",
    gridEyebrow: "کارهای منتخب",
    gridTitle: "پورتفوی پروژه",
    gridLead: "پروژه‌های فعلی و نمایندگی را بر اساس حوزه کسب‌وکار، وضعیت و ارتباط گام بعدی مرور کنید.",
    viewProject: "مشاهده پروژه",
    ctaTitle: "پروژه یا فرصت کسب‌وکاری برای گفتگو دارید؟",
    ctaLead: "برای بحث درباره مشارکت، هماهنگی پروژه یا پشتیبانی کسب‌وکار با REZAEI GLOBAL LLC تماس بگیرید.",
    contactUs: "تماس با ما",
    area: "متراژ",
    completionYear: "سال تکمیل",
    projectCategory: "دسته پروژه",
    projectOverview: "نمای کلی پروژه",
    projectSetting: "محیط پروژه",
    developmentFocus: "تمرکز توسعه",
    rezaeiRole: "نقش رضایی",
    gallery: "گالری",
    projectVisuals: "تصاویر پروژه",
    viewImage: "مشاهده تصویر",
    projectFacts: "اطلاعات پروژه",
    keyInformation: "اطلاعات کلیدی",
    location: "موقعیت",
    projectType: "نوع پروژه",
    status: "وضعیت",
    developmentType: "نوع توسعه",
    market: "بازار",
    scopeEyebrow: "دامنه مشارکت",
    scopeTitle: "مشارکت رضایی",
    relatedEyebrow: "پروژه‌های مرتبط",
    relatedTitle: "کارهای مشابه را کاوش کنید",
    detailCtaTitle: "به پروژه مشابه علاقه‌مندید؟",
    detailCtaLead:
      "درباره توسعه ملک، هماهنگی ساخت‌وساز، پشتیبانی خرید یا برنامه‌ریزی تأمین با REZAEI GLOBAL LLC صحبت کنید.",
    exploreProjects: "کاوش پروژه‌ها",
    projectGallery: "گالری پروژه",
    closeGallery: "بستن گالری",
    previousImage: "تصویر قبلی",
    nextImage: "تصویر بعدی",
    galleryAria: (title) => `گالری ${title}`,
    openGalleryImage: (title, index) => `باز کردن تصویر ${index} گالری ${title}`,
    showGalleryImage: (index) => `نمایش تصویر گالری ${index}`,
    viewProjectAria: (title) => `مشاهده ${title}`,
    defaultProjectArea: "متراژ پروژه",
    defaultLocation: "مسقط، عُمان",
    defaultMarket: "عُمان",
  },
  ar: {
    heroEyebrow: "محفظة المشاريع",
    heroTitle: "مشاريع العقارات والبناء والتطوير",
    heroLead:
      "استكشف المشاريع المختارة والاستحواذات وتنسيق البناء ومبادرات مواد البناء التي تدعمها REZAEI GLOBAL LLC.",
    heroSecondary:
      "نظرة مركّزة على الأعمال النشطة والمكتملة والمميزة عبر المجموعة، منظمة للعملاء والشركاء والمحادثات الجادة حول المشاريع.",
    statsAria: "نظرة عامة على المشاريع",
    statSelectedProjects: "مشروع مختار",
    statBusinessAreas: "مجالات الأعمال",
    statCoordinatedGroup: "مجموعة منسقة",
    coverageAria: "تغطية المشاريع",
    coverageLabel: "تغطية المشاريع",
    coverageTitle: "مسارات المحفظة المختارة",
    coverageItems: [
      "دعم الاستحواذ العقاري",
      "تنسيق البناء",
      "توريد مواد البناء",
      "دعم الإقامة والأعمال",
    ],
    viewProjects: "عرض المشاريع",
    gridEyebrow: "أعمال مختارة",
    gridTitle: "محفظة المشاريع",
    gridLead: "تصفح المشاريع الحالية والتمثيلية حسب مجال الأعمال والحالة وملاءمة الخطوة التالية.",
    viewProject: "عرض المشروع",
    ctaTitle: "هل لديك مشروع أو فرصة عمل للمناقشة؟",
    ctaLead: "تواصل مع REZAEI GLOBAL LLC لمناقشة الشراكات أو تنسيق المشاريع أو دعم الأعمال.",
    contactUs: "تواصل معنا",
    area: "المساحة",
    completionYear: "سنة الإنجاز",
    projectCategory: "فئة المشروع",
    projectOverview: "نظرة عامة على المشروع",
    projectSetting: "بيئة المشروع",
    developmentFocus: "تركيز التطوير",
    rezaeiRole: "دور رضائي",
    gallery: "المعرض",
    projectVisuals: "صور المشروع",
    viewImage: "عرض الصورة",
    projectFacts: "حقائق المشروع",
    keyInformation: "معلومات أساسية",
    location: "الموقع",
    projectType: "نوع المشروع",
    status: "الحالة",
    developmentType: "نوع التطوير",
    market: "السوق",
    scopeEyebrow: "نطاق المشاركة",
    scopeTitle: "مساهمة رضائي",
    relatedEyebrow: "مشاريع ذات صلة",
    relatedTitle: "استكشف أعمالاً مشابهة",
    detailCtaTitle: "مهتم بمشروع مشابه؟",
    detailCtaLead:
      "تحدث مع REZAEI GLOBAL LLC حول تطوير العقارات أو تنسيق البناء أو دعم الاستحواذ أو تخطيط التوريد.",
    exploreProjects: "استكشف المشاريع",
    projectGallery: "معرض المشروع",
    closeGallery: "إغلاق المعرض",
    previousImage: "الصورة السابقة",
    nextImage: "الصورة التالية",
    galleryAria: (title) => `معرض ${title}`,
    openGalleryImage: (title, index) => `فتح صورة ${index} من معرض ${title}`,
    showGalleryImage: (index) => `عرض صورة المعرض ${index}`,
    viewProjectAria: (title) => `عرض ${title}`,
    defaultProjectArea: "مساحة المشروع",
    defaultLocation: "مسقط، عُمان",
    defaultMarket: "عُمان",
  },
};

export function getProjectsPageCopy(lang) {
  return projectsPageCopy[lang] || projectsPageCopy.en;
}
