const sharedFilterValues = {
  cityOptions: ["Muscat", "Nizwa", "Salalah"],
  typeOptions: ["Villa", "Apartment", "Townhouse", "Commercial", "Land"],
  purposeOptions: ["Buy", "Rent"],
};

const constructionTypeLabels = {
  en: {
    Villa: "Villa construction",
    Apartment: "Residential building",
    Townhouse: "Housing compound",
    Commercial: "Commercial build",
    Land: "Site preparation",
  },
  tr: {
    Villa: "Villa inşaatı",
    Apartment: "Konut binası",
    Townhouse: "Konut kompleksi",
    Commercial: "Ticari yapı",
    Land: "Şantiye hazırlığı",
  },
  fa: {
    Villa: "ساخت ویلا",
    Apartment: "ساختمان مسکونی",
    Townhouse: "مجتمع مسکونی",
    Commercial: "ساخت تجاری",
    Land: "آماده‌سازی سایت",
  },
  ar: {
    Villa: "بناء فيلا",
    Apartment: "مبنى سكني",
    Townhouse: "مجمع سكني",
    Commercial: "بناء تجاري",
    Land: "تجهيز الموقع",
  },
};

const constructionPurposeLabels = {
  en: { Buy: "New build", Rent: "Renovation" },
  tr: { Buy: "Yeni yapı", Rent: "Tadilat" },
  fa: { Buy: "ساخت جدید", Rent: "بازسازی" },
  ar: { Buy: "بناء جديد", Rent: "تجديد" },
};

export const propertiesPageCopy = {
  en: {
    ...sharedFilterValues,
    heroEyebrow: "Construction capabilities",
    heroTitle: "Building, renovation, and site-ready project work.",
    heroLead:
      "This page is for construction requests, not property sales. REZAEI GLOBAL LLC supports owners and developers with building works, renovation planning, site preparation, contractor coordination, and material-linked execution.",
    searchAria: "Search construction services",
    searchPlaceholder: "Search by work type, location, or reference",
    filterLocation: "Project location",
    filterType: "Work type",
    filterPurpose: "Project stage",
    filterBudget: "Max estimate",
    filterAll: "All",
    filterAnyBudget: "Any estimate",
    budgetOptions: [
      { value: "2", label: "Up to 2M" },
      { value: "5", label: "Up to 5M" },
      { value: "10", label: "Up to 10M" },
      { value: "20", label: "Up to 20M" },
      { value: "40", label: "Up to 40M" },
    ],
    cityLabels: { Muscat: "Muscat", Nizwa: "Nizwa", Salalah: "Salalah" },
    typeLabels: constructionTypeLabels.en,
    purposeLabels: constructionPurposeLabels.en,
    inventoryEyebrow: "Work packages",
    inventoryTitle: "Construction services shaped around real project needs",
    inventoryLead: "Each card describes a construction capability or project package, including scope, site context, and the information needed for a serious first review.",
    propertiesLabel: "work packages",
    sortFeatured: "Featured first",
    sortPriceLow: "Estimate: low to high",
    sortPriceHigh: "Estimate: high to low",
    sortAria: "Sort construction work packages",
    bedsLabel: "zones",
    bathsLabel: "service cores",
    forPurposePrefix: "Stage:",
    emptyTitle: "No construction packages match these filters.",
    emptyLead: "Reset the filters or send the project scope, drawings, site location, and timing so the team can review it directly.",
    resetFilters: "Reset filters",
    prevPage: "Previous page",
    nextPage: "Next page",
    paginationAria: "Construction package pages",
    backToProperties: "Back to construction services",
    viewGallery: (count) => `View gallery · ${count} references`,
    closeGallery: "Close gallery",
    previousImage: "Previous image",
    nextImage: "Next image",
    galleryAria: (title) => `${title} reference gallery`,
    askingPrice: "Indicative estimate",
    bedrooms: "Project zones",
    bathrooms: "Service cores",
    builtUpArea: "Built-up / site area",
    overviewEyebrow: "Construction scope",
    overviewTitle: (title) => `A closer look at ${title}.`,
    overviewLead: (type, location) =>
      `This ${type.toLowerCase()} package in ${location} is presented for owners, developers, and project teams who need construction capability rather than brokerage or property sales.`,
    overviewParagraphs: [
      "The package is framed around practical construction inputs: site condition, drawings, quantities, expected finish level, delivery timing, and coordination needs. It is not a property listing or an offer to sell real estate.",
      "Our role is to help clarify the project scope, connect material and contractor requirements, and prepare a useful path for quotation, scheduling, procurement, or site execution discussions.",
      "To move forward, share drawings, location, approximate area, project stage, target budget, material preferences, and any deadline or permit constraints. The first response can then focus on buildability and next steps.",
    ],
    inquiryTitle: "Need construction support?",
    inquiryLead: "Send the project scope, drawings, site location, and timing for review.",
    makeInquiry: "Send project inquiry",
    verifiedRecord: "Construction service record",
    reference: "Reference",
    assetType: "Work type",
    market: "Project market",
    purpose: "Project stage",
    status: "Readiness",
  },
  tr: {
    ...sharedFilterValues,
    heroEyebrow: "İnşaat kabiliyetleri",
    heroTitle: "Yapım, tadilat ve şantiye hazırlığı işleri.",
    heroLead:
      "Bu sayfa emlak satışı için değildir. REZAEI GLOBAL LLC; yapı işleri, tadilat planlama, şantiye hazırlığı, yüklenici koordinasyonu ve malzemeye bağlı uygulama konularında maliklere ve geliştiricilere destek verir.",
    searchAria: "İnşaat hizmetlerinde ara",
    searchPlaceholder: "İş türü, konum veya referans ile ara",
    filterLocation: "Proje konumu",
    filterType: "İş türü",
    filterPurpose: "Proje aşaması",
    filterBudget: "Maksimum tahmin",
    filterAll: "Tümü",
    filterAnyBudget: "Her tahmin",
    budgetOptions: [
      { value: "2", label: "2M'ye kadar" },
      { value: "5", label: "5M'ye kadar" },
      { value: "10", label: "10M'ye kadar" },
      { value: "20", label: "20M'ye kadar" },
      { value: "40", label: "40M'ye kadar" },
    ],
    cityLabels: { Muscat: "Maskat", Nizwa: "Nizva", Salalah: "Salala" },
    typeLabels: constructionTypeLabels.tr,
    purposeLabels: constructionPurposeLabels.tr,
    inventoryEyebrow: "İş paketleri",
    inventoryTitle: "Gerçek proje ihtiyaçlarına göre şekillenen inşaat hizmetleri",
    inventoryLead: "Her kart; kapsam, saha bağlamı ve ilk ciddi inceleme için gereken bilgilerle bir inşaat kabiliyetini açıklar.",
    propertiesLabel: "iş paketi",
    sortFeatured: "Öne çıkanlar",
    sortPriceLow: "Tahmin: düşükten yükseğe",
    sortPriceHigh: "Tahmin: yüksekten düşüğe",
    sortAria: "İnşaat iş paketlerini sırala",
    bedsLabel: "bölge",
    bathsLabel: "servis çekirdeği",
    forPurposePrefix: "Aşama:",
    emptyTitle: "Bu filtrelere uyan inşaat paketi yok.",
    emptyLead: "Filtreleri sıfırlayın veya kapsamı, çizimleri, saha konumunu ve zamanlamayı gönderin.",
    resetFilters: "Filtreleri sıfırla",
    prevPage: "Önceki sayfa",
    nextPage: "Sonraki sayfa",
    paginationAria: "İnşaat paketi sayfaları",
    backToProperties: "İnşaat hizmetlerine dön",
    viewGallery: (count) => `Galeriyi gör · ${count} referans`,
    closeGallery: "Galeriyi kapat",
    previousImage: "Önceki görsel",
    nextImage: "Sonraki görsel",
    galleryAria: (title) => `${title} referans galerisi`,
    askingPrice: "Gösterge tahmin",
    bedrooms: "Proje bölgeleri",
    bathrooms: "Servis çekirdekleri",
    builtUpArea: "Kapalı / saha alanı",
    overviewEyebrow: "İnşaat kapsamı",
    overviewTitle: (title) => `${title} için daha yakından bakış.`,
    overviewLead: (type, location) =>
      `${location} konumundaki bu ${type.toLowerCase()} paketi, emlak satışı değil inşaat kabiliyeti arayan malik, geliştirici ve proje ekipleri içindir.`,
    overviewParagraphs: [
      "Paket; saha durumu, çizimler, miktarlar, beklenen bitiş seviyesi, teslim zamanı ve koordinasyon ihtiyacı gibi pratik inşaat girdileriyle tanımlanır.",
      "Rolümüz proje kapsamını netleştirmek, malzeme ve yüklenici ihtiyaçlarını bağlamak ve teklif, programlama, tedarik veya saha uygulaması için kullanılabilir bir yol hazırlamaktır.",
      "İlerlemek için çizimleri, konumu, yaklaşık alanı, proje aşamasını, hedef bütçeyi, malzeme tercihlerini ve süre veya izin kısıtlarını paylaşın.",
    ],
    inquiryTitle: "İnşaat desteğine mi ihtiyacınız var?",
    inquiryLead: "Proje kapsamını, çizimleri, saha konumunu ve zamanlamayı inceleme için gönderin.",
    makeInquiry: "Proje talebi gönder",
    verifiedRecord: "İnşaat hizmet kaydı",
    reference: "Referans",
    assetType: "İş türü",
    market: "Proje pazarı",
    purpose: "Proje aşaması",
    status: "Hazırlık",
  },
  fa: {
    ...sharedFilterValues,
    heroEyebrow: "توانمندی‌های ساخت‌وساز",
    heroTitle: "ساخت، بازسازی و آماده‌سازی پروژه‌های ساختمانی.",
    heroLead:
      "این صفحه برای فروش ملک یا فعالیت مشاور املاک نیست. REZAEI GLOBAL LLC به مالکان و توسعه‌دهندگان در اجرای ساختمان، برنامه‌ریزی بازسازی، آماده‌سازی سایت، هماهنگی پیمانکار و اجرای وابسته به مصالح کمک می‌کند.",
    searchAria: "جستجوی خدمات ساخت‌وساز",
    searchPlaceholder: "جستجو بر اساس نوع کار، موقعیت یا شماره مرجع",
    filterLocation: "موقعیت پروژه",
    filterType: "نوع کار",
    filterPurpose: "مرحله پروژه",
    filterBudget: "حداکثر برآورد",
    filterAll: "همه",
    filterAnyBudget: "هر برآوردی",
    budgetOptions: [
      { value: "2", label: "تا ۲ میلیون" },
      { value: "5", label: "تا ۵ میلیون" },
      { value: "10", label: "تا ۱۰ میلیون" },
      { value: "20", label: "تا ۲۰ میلیون" },
      { value: "40", label: "تا ۴۰ میلیون" },
    ],
    cityLabels: { Muscat: "مسقط", Nizwa: "نزوا", Salalah: "صلاله" },
    typeLabels: constructionTypeLabels.fa,
    purposeLabels: constructionPurposeLabels.fa,
    inventoryEyebrow: "بسته‌های کاری",
    inventoryTitle: "خدمات ساخت‌وساز متناسب با نیاز واقعی پروژه",
    inventoryLead: "هر کارت یک توانمندی یا بسته اجرایی ساختمانی را با محدوده کار، موقعیت سایت و اطلاعات لازم برای بررسی اولیه نشان می‌دهد.",
    propertiesLabel: "بسته کاری",
    sortFeatured: "موارد ویژه ابتدا",
    sortPriceLow: "برآورد: کم به زیاد",
    sortPriceHigh: "برآورد: زیاد به کم",
    sortAria: "مرتب‌سازی بسته‌های ساخت‌وساز",
    bedsLabel: "بخش",
    bathsLabel: "هسته خدمات",
    forPurposePrefix: "مرحله:",
    emptyTitle: "هیچ بسته ساخت‌وسازی با این فیلترها پیدا نشد.",
    emptyLead: "فیلترها را بازنشانی کنید یا محدوده پروژه، نقشه‌ها، موقعیت سایت و زمان‌بندی را برای بررسی مستقیم ارسال کنید.",
    resetFilters: "بازنشانی فیلترها",
    prevPage: "صفحه قبل",
    nextPage: "صفحه بعد",
    paginationAria: "صفحات بسته‌های ساخت‌وساز",
    backToProperties: "بازگشت به خدمات ساخت‌وساز",
    viewGallery: (count) => `مشاهده گالری · ${count} مرجع`,
    closeGallery: "بستن گالری",
    previousImage: "تصویر قبلی",
    nextImage: "تصویر بعدی",
    galleryAria: (title) => `گالری مرجع ${title}`,
    askingPrice: "برآورد اولیه",
    bedrooms: "بخش‌های پروژه",
    bathrooms: "هسته‌های خدماتی",
    builtUpArea: "زیربنا / مساحت سایت",
    overviewEyebrow: "محدوده ساخت",
    overviewTitle: (title) => `نگاهی دقیق‌تر به ${title}.`,
    overviewLead: (type, location) =>
      `این بسته ${type} در ${location} برای مالکان، توسعه‌دهندگان و تیم‌های پروژه است که به توان اجرایی ساخت‌وساز نیاز دارند، نه خدمات فروش یا دلالی ملک.`,
    overviewParagraphs: [
      "این بسته بر اساس ورودی‌های واقعی ساخت‌وساز تعریف می‌شود: وضعیت سایت، نقشه‌ها، مقادیر، سطح نازک‌کاری، زمان تحویل و نیازهای هماهنگی. این مورد آگهی فروش ملک نیست.",
      "نقش ما روشن کردن محدوده پروژه، اتصال نیازهای مصالح و پیمانکار، و آماده کردن مسیر مناسب برای استعلام قیمت، زمان‌بندی، تأمین یا اجرای سایت است.",
      "برای شروع، نقشه‌ها، موقعیت، متراژ تقریبی، مرحله پروژه، بودجه هدف، ترجیح مصالح و هر محدودیت زمانی یا مجوزی را ارسال کنید.",
    ],
    inquiryTitle: "به پشتیبانی ساخت‌وساز نیاز دارید؟",
    inquiryLead: "محدوده پروژه، نقشه‌ها، موقعیت سایت و زمان‌بندی را برای بررسی ارسال کنید.",
    makeInquiry: "ارسال درخواست پروژه",
    verifiedRecord: "سابقه خدمت ساخت‌وساز",
    reference: "مرجع",
    assetType: "نوع کار",
    market: "بازار پروژه",
    purpose: "مرحله پروژه",
    status: "آمادگی",
  },
  ar: {
    ...sharedFilterValues,
    heroEyebrow: "قدرات البناء",
    heroTitle: "أعمال البناء والتجديد وتجهيز المواقع.",
    heroLead:
      "هذه الصفحة ليست لبيع العقارات أو الوساطة. تدعم REZAEI GLOBAL LLC الملاك والمطورين في أعمال البناء، تخطيط التجديد، تجهيز الموقع، تنسيق المقاولين، والتنفيذ المرتبط بالمواد.",
    searchAria: "البحث في خدمات البناء",
    searchPlaceholder: "ابحث حسب نوع العمل أو الموقع أو المرجع",
    filterLocation: "موقع المشروع",
    filterType: "نوع العمل",
    filterPurpose: "مرحلة المشروع",
    filterBudget: "أقصى تقدير",
    filterAll: "الكل",
    filterAnyBudget: "أي تقدير",
    budgetOptions: [
      { value: "2", label: "حتى 2M" },
      { value: "5", label: "حتى 5M" },
      { value: "10", label: "حتى 10M" },
      { value: "20", label: "حتى 20M" },
      { value: "40", label: "حتى 40M" },
    ],
    cityLabels: { Muscat: "مسقط", Nizwa: "نزوى", Salalah: "صلالة" },
    typeLabels: constructionTypeLabels.ar,
    purposeLabels: constructionPurposeLabels.ar,
    inventoryEyebrow: "حزم العمل",
    inventoryTitle: "خدمات بناء مصممة حول احتياجات المشروع الفعلية",
    inventoryLead: "توضح كل بطاقة قدرة إنشائية أو حزمة عمل، مع النطاق وسياق الموقع والمعلومات اللازمة للمراجعة الأولى.",
    propertiesLabel: "حزمة عمل",
    sortFeatured: "المميز أولاً",
    sortPriceLow: "التقدير: من الأقل إلى الأعلى",
    sortPriceHigh: "التقدير: من الأعلى إلى الأقل",
    sortAria: "ترتيب حزم أعمال البناء",
    bedsLabel: "مناطق",
    bathsLabel: "نوى خدمات",
    forPurposePrefix: "المرحلة:",
    emptyTitle: "لا توجد حزم بناء تطابق هذه الفلاتر.",
    emptyLead: "أعد ضبط الفلاتر أو أرسل نطاق المشروع والرسومات وموقع الموقع والجدول الزمني للمراجعة.",
    resetFilters: "إعادة ضبط الفلاتر",
    prevPage: "الصفحة السابقة",
    nextPage: "الصفحة التالية",
    paginationAria: "صفحات حزم البناء",
    backToProperties: "العودة إلى خدمات البناء",
    viewGallery: (count) => `عرض المعرض · ${count} مراجع`,
    closeGallery: "إغلاق المعرض",
    previousImage: "الصورة السابقة",
    nextImage: "الصورة التالية",
    galleryAria: (title) => `معرض مراجع ${title}`,
    askingPrice: "تقدير مبدئي",
    bedrooms: "مناطق المشروع",
    bathrooms: "نوى الخدمات",
    builtUpArea: "المساحة المبنية / الموقع",
    overviewEyebrow: "نطاق البناء",
    overviewTitle: (title) => `نظرة أقرب على ${title}.`,
    overviewLead: (type, location) =>
      `حزمة ${type} في ${location} مخصصة للملاك والمطورين وفرق المشاريع التي تحتاج إلى قدرة تنفيذ إنشائية، وليس إلى بيع أو وساطة عقارية.`,
    overviewParagraphs: [
      "تُعرض الحزمة حول مدخلات البناء العملية: حالة الموقع، الرسومات، الكميات، مستوى التشطيب، توقيت التسليم، واحتياجات التنسيق. وليست إعلان بيع عقار.",
      "دورنا هو توضيح نطاق المشروع، ربط احتياجات المواد والمقاولين، وتجهيز مسار مفيد للتسعير أو الجدولة أو التوريد أو التنفيذ في الموقع.",
      "للمتابعة، أرسل الرسومات والموقع والمساحة التقريبية ومرحلة المشروع والميزانية المستهدفة وتفضيلات المواد وأي قيود متعلقة بالوقت أو التصاريح.",
    ],
    inquiryTitle: "هل تحتاج إلى دعم إنشائي؟",
    inquiryLead: "أرسل نطاق المشروع والرسومات وموقع الموقع والجدول الزمني للمراجعة.",
    makeInquiry: "إرسال طلب مشروع",
    verifiedRecord: "سجل خدمة بناء",
    reference: "المرجع",
    assetType: "نوع العمل",
    market: "سوق المشروع",
    purpose: "مرحلة المشروع",
    status: "الجاهزية",
  },
};

export function getPropertiesPageCopy(lang) {
  return propertiesPageCopy[lang] || propertiesPageCopy.en;
}
