# Generated by Django 5.1.4 on 2026-06-09 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_slug', models.CharField(blank=True, max_length=255)),
                ('locale', models.CharField(default='en', max_length=12)),
                ('name', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=80)),
                ('company', models.CharField(blank=True, max_length=160)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('subject', models.CharField(blank=True, max_length=220)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('contacted', 'Contacted'), ('closed', 'Closed')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='content.site')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['site', 'status', 'created_at'], name='content_inq_site_id_49d775_idx'), models.Index(fields=['email', 'created_at'], name='content_inq_email_8e9a30_idx')],
            },
        ),
    ]
